### ISSUE TITLE
Log tailing does not stop on pressing pause button

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#10]
The logs continue to tail in dashboard-v2, even when I pause logging.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 I could not reproduce this on prod. Are there more specific steps?

**Comment by sukrit007** [comment]
I tried it again and i am unable to reproduce it either.  If it happens again, I will try to capture more ino and will re-open the issue.
