### ISSUE TITLE
Visualization for totem events

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#11]
As a developer, I would like to see the totem events visualized as charts capturing time taken for each of the step.  Here are the list of steps that can be visualized:
- Build Image time
- Travis/CI time
- Deploy Image time
- Deployment Validation time
- Deployment Promotion time

@mmoulton  could you attach an example of chart that you described ?

**Comment by 10xLaCroixDrinker** [comment]
Since there are so many changes to the selected deployment view in #9, I am going to branch off of that to start this work.

**Comment by 10xLaCroixDrinker** [comment]
Here is what I have currently:
![screen shot 2015-08-24 at 9 21 35 am](https://cloud.githubusercontent.com/assets/517295/9445556/9814f856-4a41-11e5-8987-25cedbda67f0.png)

I'm going to need some more info in order to make these more human readable. Also which events need to be displayed, which don't, etc.

@mmoulton @sukrit007

**Comment by sukrit007** [comment]
@jking90  I am working on an example. Once done, will attach it to this ticket.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 @mmoulton Here is what I have so far:

![screen shot 2015-08-27 at 9 20 11 am](https://cloud.githubusercontent.com/assets/517295/9526228/ddd4cd78-4c9c-11e5-98f9-212057544272.png)

I am not seeing any events with the type `CALLBACK_HOOK` per the event mapping you gave me @sukrit007

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 @mmoulton updated:

![screen shot 2015-08-28 at 9 37 12 am](https://cloud.githubusercontent.com/assets/517295/9551836/89497b6a-4d68-11e5-87b8-74a5e1e55f95.png)

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 @mmoulton This should be resolved by #23. See the latest screenshot there.
