### ISSUE TITLE
Dashboard freezes at times

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#14]
A lot of times when we are navigating through dashboard and changing dropdown selections, dashboard will freeze.

**Comment by sukrit007** [comment]
@jking90   Whenever you have time, you can look at this one.  If needed , I can try to send exact steps for the same and  it happens very frequently.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 Exact steps to reproduce would be very helpful

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 running the develop branch locally, I selected different deployment from the dropdown on `http://localhost:3000/#/apps/totem/cluster-deployer/develop` over 50 times without reproducing, same process and result on `http://localhost:3000/#/apps/totem/config/develop`
