### ISSUE TITLE
Address for upstream

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#17]
For selected deployment,  I would like to see the  link  to physical host with port)

Note:  The yoda register process has been extended to support ec2 metadata tags. In short for ec2 deployed environment we are now using  ec2 public hostname for upstream.

**Comment by sukrit007** [comment]
Based on discussion with @kennedyj   we also need to some way to co-releate the unit with upstream.  Currently , we were using  private address.   

I will investigate on how we can change the publish information to be more structured.

**Comment by sukrit007** [comment]
@kennedyj  @jking90    I have added a new attribute in runtime called 'proxy-upstreams'    This new field has a lot of information for co-releating services and upstreams.   Let me know if that works.

Example deploy: cluster-deployer  in development

**Comment by sukrit007** [comment]
I have simplified the ports view so that it is less confusing.   Let me know your thoughts.
Note:  With new data, we can easily find port mappings for a given service.

![image](https://cloud.githubusercontent.com/assets/758708/9530879/636231a0-4cb7-11e5-8758-4e70bb7b64ad.png)

@kennedyj  @mmoulton  @jking90   Let me know your thoughts.  

Note:  THere will be links for individual port entries that would take to appropriate port on the host.

**Comment by kennedyj** [comment]
Looks good, are the ports links to the translated port on the machine?

**Comment by sukrit007** [comment]
Thats correct. It links to translated port.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 This should be resolved by #22
