### ISSUE TITLE
Viewing decomissioned and deleted Deployments

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#18]
Current version of dashboard does not show deleted/failed deployments for a given branch , if the latest version of the given branch is un-deployed.  The reason that was added was to avoid clutter as there was no TTL defined.

Now that we have TTL defined for de-comissioned/failed deployments,  I would like to see the list of failed and decommissioned deploys for given branch (TTL will automatically take care of old deployments. Currently TTL is set for 1 month and can be adjusted if need be)

@mmoulton @ctrimble @kennedyj @jking90   Thoughts / Comments ?  Please update this ticket.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 #21 will get rid of filters that are hiding decommissioned deployments
