### ISSUE TITLE
Delete: Need confirmation prior to deleting a deployment

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#24]
As a totem user, I would like to see a confirmation dialog prior to deleting deployment from dashboard so that I do not accidentally end up deleting an existing deployment.

@mmoulton @jking90  @kennedyj   I think to start off we can throw in  a basic dialog (Yes/No)  with default option as "No"  .  Thoughts ?

**Comment by 10xLaCroixDrinker** [comment]
I implemented this using `$mdDialog`.

![screen shot 2015-08-31 at 7 06 17 am](https://cloud.githubusercontent.com/assets/517295/9580520/e7f51fbe-4fae-11e5-824b-bac475440ddb.png)

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 since there has been no feedback on this, I opened PR #27 to implement the proposed solution

**Comment by sukrit007** [comment]
Verified. Looks good.    Just a thought,  should  we keep the default option as "NO" instead of "YES" ?   Rest looks good.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 the default is now "no" per the requirements
