### ISSUE TITLE
Ability to activate previous deployed version

### ISSUE THREAD

**Issue by sukrit007** [totem/dashboard-v2#26]
As  a totem user, I need the ability to rollback to previous deployed version in scenarios where current version of application is not stable.

AC
- Re-activate button should only be shown applications that are in: DECOMMISSIONED, FAILED states

API Call:
TBD:   Need to fix state management API call for a deployment. Though posting ful job information achieves the same, but will fix this API and update this ticket.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 do we have the API call for this yet?

**Comment by 10xLaCroixDrinker** [comment]
provided by @sukrit007

`PATCH /apps/{{appName}}/versions/{{version}}` with body: `{state: 'NEW'}`

**Comment by sukrit007** [comment]
@jking90   Since I already had a recovery API,  I ended up modifying that

```
POST /recovery
Content-Type: application/vnd.deployer.recovery.v1+json
```

Data: 

``` json
{
   "name":  "<deployment name>"
   "version":  "<version for the deployment>"
   "state":  "<current state of deployment>"
}
```

The change is pushed to thorium.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 the `Content-Type` header is not allowed on that service:

```
XMLHttpRequest cannot load https://{{ deployerUrl (thorium) }}/recovery. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
```

**Comment by sukrit007** [comment]
For now , do not pass the header.   I will investigate on why CORS filter
is creating this issue on BE service.  Even if you do not pass any header,
it should still work fine as it defaults to v1.  Once I fix CORS issue, i
will let you know.

On Wed, Sep 16, 2015 at 8:41 AM, Jimmy King notifications@github.com
wrote:

> @sukrit007 https://github.com/sukrit007 the Content-Type header is not
> allowed on that service:
> 
> XMLHttpRequest cannot load https://{{ deployerUrl (thorium) }}/recovery. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/totem/dashboard-v2/issues/26#issuecomment-140781207.

##

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 posting without the header results in the following error:

```
POST https://{{ deployerUrl }}/recovery 415 (UNSUPPORTED MEDIA TYPE)
```

**Comment by sukrit007** [comment]
CORS issue is now fixed  @jking90 

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Authorization, Content-Type
< Access-Control-Expose-Headers: Content-Length, Content-Type, E-Tag, If-Modified-Since, Link, Location
< Access-Control-Allow-Credentials: true
```

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 PR #31 is ready
