### ISSUE TITLE
As a developer I want to know how long a build has been deployed

### ISSUE THREAD

**Issue by mmoulton** [totem/dashboard-v2#28]
Add relative timestamps for when a branch was deployed both to the dashboard and the detail page.

For example:

```
meltmedia/talu-website
master: up 32 days  |  develop: up 1 hour
```

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 to add a date indicating when a deployment entered its current state to deployment object

**Comment by sukrit007** [comment]
@jking90   Added attribute:   state-updated in thorium.   This attribute will be updated only when state transition occurs.  However, it will only be available for new deployments. For existing deployments, we can show "NA" i.e. Not Available.

Here is an example deployment with this attribute:
[http://totem.r53.us-west-1.th.melt.sh/#/apps/totem/totem-demo/develop](http://totem.r53.us-west-1.th.melt.sh/#/apps/totem/totem-demo/develop)

Let me know if this works.
